# FLETCHER REEVES PYTHON CODE BY UDITA CHATTERJEE



Without using  the loops

for 2nd degree polynomial






In [58]:
import numpy as np
import numpy.linalg as npl
import matplotlib.pyplot as plt
import sympy as sym
from sympy import *


In [94]:
x=sym.symbols('x')
y=sym.symbols('y')
f=x**2+y**2+2*x+2*y+2
f
dx=f.diff(x) #differentiation wrt x
dx
dy=f.diff(y) #differentiation wrt y
dy
dx=sym.lambdify([x,y],dx)
dy=sym.lambdify([x,y],dy)
f=sym.lambdify([x,y],f)
X1=np.array([0,0]) #step1 initializing by taking a vector X1

S1=np.array((2,1))
S1[0]=-dx(X1[0],X1[1])
S1[1]=-dy(X1[0],X1[1])
S1 #-Grad of f(X) at the point X1
X2=np.array((2,1))

#Step 2
#X2=X1+lambda*S1

#from sympy import *
#z=Symbol('z')

z=sym.symbols('z')
x=sym.symbols('x')
y=sym.symbols('y')
x=X1[0]+z*S1[0]
y=X1[1]+z*S1[1]
p=x**2+y**2+2*x+2*y+2

dif=p.diff(z)
v=sym.solve(dif,z)  #gives list value
v
v1=v[0]
v1
print(v1)
X2[0]=X1[0]+v1*S1[0]
X2[1]=X1[1]+v1*S1[1]

grad_f2=np.array((2,1))

grad_f2[0]=dx(X2[0],X2[1])
grad_f2[1]=dy(X2[0],X2[1])

#S2=-grad(f_i)+ 

norm2=npl.norm(grad_f2)
norm=npl.norm(S1)
k=(norm2*norm2)/(norm*norm)

S2=np.array((2,1))

S2[0]=-grad_f2[0]+k*S1[0]
S2[1]=-grad_f2[1]+k*S1[1]
S2

X3=np.array((2,1))

#step 4 
q=sym.symbols('q')
x=sym.symbols('x')
y=sym.symbols('y')
x=X2[0]+q*S2[0]
y=X2[1]+q*S2[1]
p=x**2+y**2+2*x+2*y+2

dif=p.diff(q)
v=sym.solve(dif,q)  #gives list value
v
v1=v[0]
v1
print(v1)
X3[0]=X2[0]+v1*S2[0]
X3[1]=X2[1]+v1*S2[1]
X3

   
#as X2=X3 
#hence the optimal value is at X2


#-3
X2,X3










1/2


IndexError: list index out of range

In [74]:
z=sym.symbols('z')
x=sym.symbols('x')
y=sym.symbols('y')
x=X1[0]+z*S1[0]
y=X1[1]+z*S1[1]
p=x**2+y**2+2*x+2*y+2

dif=p.diff(z)
dif
v=sym.solve(dif,z)
v[0]

1/2

In [84]:
z=sym.symbols('z')
x=sym.symbols('x')
y=sym.symbols('y')
x=X2[0]+z*S2[0]
y=X2[1]+z*S2[1]
p=x**2+y**2+2*x+y+2

dif=p.diff(z)
S1


array([-2, -2])

In [85]:
k

0.0

In [86]:
norm2

0.0

In [87]:
npl.norm(grad_f2)

0.0

In [88]:
grad_f2

array([0, 0])

0

In [93]:
S1=np.array((2,1))
S1[0]=-dx(X1[0],X1[1])
S1[1]=-dy(X1[0],X1[1])
S1

array([-2, -2])

In [98]:
z=sym.symbols('z')
x=sym.symbols('x')
y=sym.symbols('y')
x=X1[0]+z*S1[0]
y=X1[1]+z*S1[1]
p=x**2+y**2+2*x+2*y+2

dif=p.diff(z)
v=sym.solve(dif,z)  #gives list value
v

[1/2]

In [99]:
X2

array([-1, -1])

In [100]:
X3

array([2, 1])

In [104]:
grad_f2=np.array((2,1))

grad_f2[0]=dx(X2[0],X2[1])
grad_f2[1]=dy(X2[0],X2[1])

dx[X2[0],X2[1]]


TypeError: 'function' object is not subscriptable